### ISSUE TITLE
Error: Cannot find module 'express'

### ISSUE THREAD

**Issue by as409** [twilio/twilio-chat-demo-js#24]
module.js:328
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/akhil/Desktop/twilio-chat-demo-js-master/server.js:2:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

npm ERR! Linux 4.8.0-54-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! twilio-chat-demo-js@0.11.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the twilio-chat-demo-js@0.11.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the twilio-chat-demo-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs twilio-chat-demo-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls twilio-chat-demo-js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/akhil/Desktop/twilio-chat-demo-js-master/npm-debug.log

**Comment by almeidamarcell** [comment]
Same problem here. How did you solved it?

**Comment by philnash** [comment]
@almeidamarcell That is a missing dependency error from npm. Ensure that you have run `npm install` before you try to start the application.
