### ISSUE TITLE
 module.js:328     throw err;

### ISSUE THREAD

**Issue by as409** [twilio/twilio-chat-demo-js#25]
npm start

> twilio-chat-demo-js@0.11.0 start /home/akhil/Desktop/twilio-chat-demo-js-master
> node server.js

module.js:328
    throw err;
    ^

Error: Cannot find module 'twilio'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/akhil/Desktop/twilio-chat-demo-js-master/lib/tokenprovider.js:3:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

**Comment by superdreams** [comment]
same prolem

**Comment by nsatyan** [comment]
me to
